#!/bin/sh


case "$1" in
	start)
		echo "Starting ldd drivers"
		scull_load
		module_load faulty
		modprobe hello.ko
		aesdchar_load
		;;
	stop)
		echo "Stopping ldd drivers"
		scull_unload
		module_unload faulty
		rmmod hello.ko
		aesdchar_unload
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
